AWSTemplateFormatVersion: "2010-09-09"
Description: Create a lamada function

Resources:
  LamadaFunctionPolicy:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: "lambda-traning-zhangtian"
        S3Key: "zipFile.zip"

      FunctionName: "zhangtian-cloudformation"
      Handler: "index.run"
      Role: "arn:aws:iam::494526681395:role/for-aws-training"
      Runtime: "nodejs10.x"

